version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - VUE_APP_BE_ADDRESS=http://backend:8081
      - WAIT_HOSTS=backend:8081

  backend:
    build:
      context: ./backend
    environment:
      - PORT=8081
      - FE_ADDRESS=http://frontend:8080
      - CONNECTION_STRING=mongodb://database:27017/shortener
      - WAIT_HOSTS=database:27017
      
  database:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-data-config:/data/configdb

volumes:
  mongo-data:
  mongo-data-config:
