version: "3.8"

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CONNECTION_STRING=mongodb://database:27017/shortener
      - FE_ADDRESS=http://localhost:8081
      - WAIT_HOSTS=database:27017
      
  database:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-data-config:/data/configdb

volumes:
  mongo-data:
  mongo-data-config:
